name: GabrielCopa deploy
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install packages
        run: npm i
      - name: Run ESLint Next
        run: npm run lint
      - name: Bundle
        run: npm run build